package projekt;
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue May 30 18:46:32 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WIEKSZYROWNY = 10;
  public static final int ZMIENNA = 7;
  public static final int ROWNY = 8;
  public static final int POTEGA = 6;
  public static final int MNIEJSZY = 11;
  public static final int MNOZENIE = 5;
  public static final int liczba = 13;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int WIEKSZY = 9;
  public static final int MNIEJSZYROWNY = 12;
  public static final int DZIELENIE = 4;
  public static final int ODEJMOWANIE = 3;
  public static final int DODAWANIE = 2;
}

